#!/bin/bash
#automatic generate dependence for each c cource file
echo "----------------compile the code---------------"
make -B -f makefile_1
#makefile 
make -f makefile_3
#info
echo "please use .txt for output"